name: 'Setup pandoc'
author: 'Albert Krewinkel'
description: 'Installs pandoc from the official binaries.'
inputs:
  version:
    description: 'The version of pandoc to be installed.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Choose which installer to use'
      shell: bash
      run: |
        case $RUNNER_OS in
          "Linux")
              printf 'INSTALLER_SUFFIX=1-amd64.deb' >> $GITHUB_ENV
              ;;
           "macOS")
              printf 'INSTALLER_SUFFIX=macOS.pkg' >> $GITHUB_ENV
              ;;
            *)
              printf 'Do not know how to install pandoc on %s\n' "$RUNNER_OS"
              exit 1
              ;;
        esac

    - name: 'Download installer'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPO: jgm/pandoc
        DOWNLOAD_URL: 'https://github.com/jgm/pandoc/releases/download/'
      run: |
        gh release download ${{ inputs.version }} \
            --repo "$REPO" \
            --pattern '*'${{ env.INSTALLER_SUFFIX }}
        printf 'INSTALLER_VERSION=%s' \
               "$(ls pandoc-*-${{ env.INSTALLER_SUFFIX }} | \
                      sed 's/pandoc-\([0-9.]*\)-.*/\1/')" \
               >> $GITHUB_ENV

    - name: 'Install pandoc'
      shell: bash
      env:
        INSTALLER: pandoc-${{ env.INSTALLER_VERSION }}-${{ env.INSTALLER_SUFFIX }}
      run: |
        case $RUNNER_OS in
          "Linux")
              sudo apt install ./$INSTALLER
              ;;
           "macOS")
              sudo installer -pkg ./$INSTALLER -target '/'
              ;;
            *)
              echo "$RUNNER_OS not supported"
              exit 1
              ;;
        esac
        rm $INSTALLER
